name: Draw Keymap
on:
  workflow_dispatch: # Allows manual trigger
  push:              # Automatically run on changes
    paths:
      - "config/*.keymap"
      - "keymap_drawer.config.yaml"

jobs:
  draw:
    uses: caksoylar/keymap-drawer/.github/workflows/draw-zmk.yml@main
    permissions:
      contents: write  # Required to commit the SVG back to your repo
    with:
      keymap_patterns: "config/*.keymap"
      output_folder: "keymap-drawer"
